services:
    postgres:
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/18/docker
        volumes:
            - postgres:/var/lib/postgresql
        ports:
            - "5432:5432"
        image: postgres:18

volumes:
    postgres:
